{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "xz",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "xz",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "xz",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "xz",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4",
      "fix_state": "Not affected",
      "package_name": "rhcos",
      "cpe": "cpe:/a:redhat:openshift:4"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2025-04-03T16:57:05Z",
  "bugzilla": {
    "description": "xz: XZ has a heap-use-after-free bug in threaded .xz decoder",
    "id": "2357249",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2357249"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "(CWE-366|CWE-416|CWE-476|CWE-826)",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2025-31115",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2025-31115\nhttps://nvd.nist.gov/vuln/detail/CVE-2025-31115\nhttps://github.com/tukaani-project/xz/commit/d5a2ffe41bb77b918a8c96084885d4dbe4bf6480\nhttps://github.com/tukaani-project/xz/security/advisories/GHSA-6cc8-p5mm-29w2\nhttps://tukaani.org/xz/xz-cve-2025-31115.patch"
  ]
}