{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2025-03-27T00:00:00Z",
  "bugzilla": {
    "description": "kernel: can: j1939: fix errant WARN_ON_ONCE in j1939_session_deactivate",
    "id": "2355529",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2355529"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "3.3",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2021-4454",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\ncan: j1939: fix errant WARN_ON_ONCE in j1939_session_deactivate\nThe conclusion \"j1939_session_deactivate() should be called with a\nsession ref-count of at least 2\" is incorrect. In some concurrent\nscenarios, j1939_session_deactivate can be called with the session\nref-count less than 2. But there is not any problem because it\nwill check the session active state before session putting in\nj1939_session_deactivate_locked().\nHere is the concurrent scenario of the problem reported by syzbot\nand my reproduction log.\ncpu0                            cpu1\nj1939_xtp_rx_eoma\nj1939_xtp_rx_abort_one\nj1939_session_get_by_addr [kref == 2]\nj1939_session_get_by_addr [kref == 3]\nj1939_session_deactivate [kref == 2]\nj1939_session_put [kref == 1]\nj1939_session_completed\nj1939_session_deactivate\nWARN_ON_ONCE(kref \u003c 2)\n=====================================================\nWARNING: CPU: 1 PID: 21 at net/can/j1939/transport.c:1088 j1939_session_deactivate+0x5f/0x70\nCPU: 1 PID: 21 Comm: ksoftirqd/1 Not tainted 5.14.0-rc7+ #32\nHardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-1ubuntu1 04/01/2014\nRIP: 0010:j1939_session_deactivate+0x5f/0x70\nCall Trace:\nj1939_session_deactivate_activate_next+0x11/0x28\nj1939_xtp_rx_eoma+0x12a/0x180\nj1939_tp_recv+0x4a2/0x510\nj1939_can_recv+0x226/0x380\ncan_rcv_filter+0xf8/0x220\ncan_receive+0x102/0x220\n? process_backlog+0xf0/0x2c0\ncan_rcv+0x53/0xf0\n__netif_receive_skb_one_core+0x67/0x90\n? process_backlog+0x97/0x2c0\n__netif_receive_skb+0x22/0x80"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2021-4454\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-4454\nhttps://lore.kernel.org/linux-cve-announce/2025032716-CVE-2021-4454-f4a4@gregkh/T"
  ]
}