{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2024-12-27T00:00:00Z",
  "bugzilla": {
    "description": "kernel: netfilter: x_tables: fix LED ID check in led_tg_check()",
    "id": "2334554",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2334554"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-56650",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nnetfilter: x_tables: fix LED ID check in led_tg_check()\nSyzbot has reported the following BUG detected by KASAN:\nBUG: KASAN: slab-out-of-bounds in strlen+0x58/0x70\nRead of size 1 at addr ffff8881022da0c8 by task repro/5879\n...\nCall Trace:\n\u003cTASK\u003e\ndump_stack_lvl+0x241/0x360\n? __pfx_dump_stack_lvl+0x10/0x10\n? __pfx__printk+0x10/0x10\n? _printk+0xd5/0x120\n? __virt_addr_valid+0x183/0x530\n? __virt_addr_valid+0x183/0x530\nprint_report+0x169/0x550\n? __virt_addr_valid+0x183/0x530\n? __virt_addr_valid+0x183/0x530\n? __virt_addr_valid+0x45f/0x530\n? __phys_addr+0xba/0x170\n? strlen+0x58/0x70\nkasan_report+0x143/0x180\n? strlen+0x58/0x70\nstrlen+0x58/0x70\nkstrdup+0x20/0x80\nled_tg_check+0x18b/0x3c0\nxt_check_target+0x3bb/0xa40\n? __pfx_xt_check_target+0x10/0x10\n? stack_depot_save_flags+0x6e4/0x830\n? nft_target_init+0x174/0xc30\nnft_target_init+0x82d/0xc30\n? __pfx_nft_target_init+0x10/0x10\n? nf_tables_newrule+0x1609/0x2980\n? nf_tables_newrule+0x1609/0x2980\n? rcu_is_watching+0x15/0xb0\n? nf_tables_newrule+0x1609/0x2980\n? nf_tables_newrule+0x1609/0x2980\n? __kmalloc_noprof+0x21a/0x400\nnf_tables_newrule+0x1860/0x2980\n? __pfx_nf_tables_newrule+0x10/0x10\n? __nla_parse+0x40/0x60\nnfnetlink_rcv+0x14e5/0x2ab0\n? __pfx_validate_chain+0x10/0x10\n? __pfx_nfnetlink_rcv+0x10/0x10\n? __lock_acquire+0x1384/0x2050\n? netlink_deliver_tap+0x2e/0x1b0\n? __pfx_lock_release+0x10/0x10\n? netlink_deliver_tap+0x2e/0x1b0\nnetlink_unicast+0x7f8/0x990\n? __pfx_netlink_unicast+0x10/0x10\n? __virt_addr_valid+0x183/0x530\n? __check_object_size+0x48e/0x900\nnetlink_sendmsg+0x8e4/0xcb0\n? __pfx_netlink_sendmsg+0x10/0x10\n? aa_sock_msg_perm+0x91/0x160\n? __pfx_netlink_sendmsg+0x10/0x10\n__sock_sendmsg+0x223/0x270\n____sys_sendmsg+0x52a/0x7e0\n? __pfx_____sys_sendmsg+0x10/0x10\n__sys_sendmsg+0x292/0x380\n? __pfx___sys_sendmsg+0x10/0x10\n? lockdep_hardirqs_on_prepare+0x43d/0x780\n? __pfx_lockdep_hardirqs_on_prepare+0x10/0x10\n? exc_page_fault+0x590/0x8c0\n? do_syscall_64+0xb6/0x230\ndo_syscall_64+0xf3/0x230\nentry_SYSCALL_64_after_hwframe+0x77/0x7f\n...\n\u003c/TASK\u003e\nSince an invalid (without '\\0' byte at all) byte sequence may be passed\nfrom userspace, add an extra check to ensure that such a sequence is\nrejected as possible ID and so never passed to 'kstrdup()' and further."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-56650\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-56650\nhttps://lore.kernel.org/linux-cve-announce/2024122740-CVE-2024-56650-4d51@gregkh/T"
  ]
}