{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2024-08-26T00:00:00Z",
  "bugzilla": {
    "description": "kernel: f2fs: fix to do sanity check on F2FS_INLINE_DATA flag in inode during GC",
    "id": "2307901",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2307901"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.1",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-99",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-44942",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nf2fs: fix to do sanity check on F2FS_INLINE_DATA flag in inode during GC\nsyzbot reports a f2fs bug as below:\n------------[ cut here ]------------\nkernel BUG at fs/f2fs/inline.c:258!\nCPU: 1 PID: 34 Comm: kworker/u8:2 Not tainted 6.9.0-rc6-syzkaller-00012-g9e4bc4bcae01 #0\nRIP: 0010:f2fs_write_inline_data+0x781/0x790 fs/f2fs/inline.c:258\nCall Trace:\nf2fs_write_single_data_page+0xb65/0x1d60 fs/f2fs/data.c:2834\nf2fs_write_cache_pages fs/f2fs/data.c:3133 [inline]\n__f2fs_write_data_pages fs/f2fs/data.c:3288 [inline]\nf2fs_write_data_pages+0x1efe/0x3a90 fs/f2fs/data.c:3315\ndo_writepages+0x35b/0x870 mm/page-writeback.c:2612\n__writeback_single_inode+0x165/0x10b0 fs/fs-writeback.c:1650\nwriteback_sb_inodes+0x905/0x1260 fs/fs-writeback.c:1941\nwb_writeback+0x457/0xce0 fs/fs-writeback.c:2117\nwb_do_writeback fs/fs-writeback.c:2264 [inline]\nwb_workfn+0x410/0x1090 fs/fs-writeback.c:2304\nprocess_one_work kernel/workqueue.c:3254 [inline]\nprocess_scheduled_works+0xa12/0x17c0 kernel/workqueue.c:3335\nworker_thread+0x86d/0xd70 kernel/workqueue.c:3416\nkthread+0x2f2/0x390 kernel/kthread.c:388\nret_from_fork+0x4d/0x80 arch/x86/kernel/process.c:147\nret_from_fork_asm+0x1a/0x30 arch/x86/entry/entry_64.S:244\nThe root cause is: inline_data inode can be fuzzed, so that there may\nbe valid blkaddr in its direct node, once f2fs triggers background GC\nto migrate the block, it will hit f2fs_bug_on() during dirty page\nwriteback.\nLet's add sanity check on F2FS_INLINE_DATA flag in inode during GC,\nso that, it can forbid migrating inline_data inode's data block for\nfixing."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-44942\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-44942\nhttps://lore.kernel.org/linux-cve-announce/2024082620-CVE-2024-44942-651a@gregkh/T"
  ]
}