{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "virtuoso-opensource",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-01-14T00:00:00Z",
  "bugzilla": {
    "description": "virtuoso-opensource: DoS in chash_array",
    "id": "2337507",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2337507"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-57635",
  "document_distribution": "",
  "details": [
    "An issue in the chash_array component of openlink virtuoso-opensource v7.2.11 allows attackers to cause a Denial of Service (DoS) via crafted SQL statements."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-57635\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-57635\nhttps://github.com/openlink/virtuoso-opensource/issues/1182"
  ]
}