{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat OpenShift Container Platform 4",
      "fix_state": "Fix deferred",
      "package_name": "ose-aws-efs-utils-container",
      "cpe": "cpe:/a:redhat:openshift:4"
    },
    {
      "product_name": "Service Telemetry Framework 1.5 for RHEL 8",
      "fix_state": "Fix deferred",
      "package_name": "stf/prometheus-webhook-snmp-rhel8",
      "cpe": "cpe:/a:redhat:service_telemetry_framework:1.5::el8"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2022-10-16T00:00:00Z",
  "bugzilla": {
    "description": "py: ReDoS in py library when used with subversion",
    "id": "2312846",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2312846"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "3.1",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-1333",
  "statement": "This has been disputed by multiple parties, including the upstream maintainers, as not being reproducible or a valid vulnerability.",
  "acknowledgement": "",
  "name": "CVE-2022-42969",
  "document_distribution": "",
  "details": [
    "The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled. Note: This has been disputed by multiple third parties as not being reproduceable and they argue this is not a valid vulnerability."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-42969\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-42969"
  ]
}