{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-02-26T00:00:00Z",
  "bugzilla": {
    "description": "kernel: rtw89: cfo: check mac_id to avoid out-of-bounds",
    "id": "2348322",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2348322"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-49471",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nrtw89: cfo: check mac_id to avoid out-of-bounds\nSomehow, hardware reports incorrect mac_id and pollute memory. Check index\nbefore we access the array.\nUBSAN: array-index-out-of-bounds in rtw89/phy.c:2517:23\nindex 188 is out of range for type 's32 [64]'\nCPU: 1 PID: 51550 Comm: irq/35-rtw89_pc Tainted: G           OE\nCall Trace:\n\u003cIRQ\u003e\nshow_stack+0x52/0x58\ndump_stack_lvl+0x4c/0x63\ndump_stack+0x10/0x12\nubsan_epilogue+0x9/0x45\n__ubsan_handle_out_of_bounds.cold+0x44/0x49\n? __alloc_skb+0x92/0x1d0\nrtw89_phy_cfo_parse+0x44/0x7f [rtw89_core]\nrtw89_core_rx+0x261/0x871 [rtw89_core]\n? __alloc_skb+0xee/0x1d0\nrtw89_pci_napi_poll+0x3fa/0x4ea [rtw89_pci]\n__napi_poll+0x33/0x1a0\nnet_rx_action+0x126/0x260\n? __queue_work+0x217/0x4c0\n__do_softirq+0xd9/0x315\n? disable_irq_nosync+0x10/0x10\ndo_softirq.part.0+0x6d/0x90\n\u003c/IRQ\u003e\n\u003cTASK\u003e\n__local_bh_enable_ip+0x62/0x70\nrtw89_pci_interrupt_threadfn+0x182/0x1a6 [rtw89_pci]\nirq_thread_fn+0x28/0x60\nirq_thread+0xc8/0x190\n? irq_thread_fn+0x60/0x60\nkthread+0x16b/0x190\n? irq_thread_check_affinity+0xe0/0xe0\n? set_kthread_struct+0x50/0x50\nret_from_fork+0x22/0x30\n\u003c/TASK\u003e"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-49471\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-49471\nhttps://lore.kernel.org/linux-cve-announce/2025022602-CVE-2022-49471-4e82@gregkh/T"
  ]
}